################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
from setuptools import setup

setup(
    name = "application_network_cffi",
    version = "0.0.2",
    license = "mplv2",
    description = """Python cffi bindings of: a network for sharing data and actions in a network""",
    packages = ["application_network_cffi", ],
    setup_requires=["cffi"],
    cffi_modules=[
           "application_network_cffi/build.py:ffibuilder",
           "application_network_cffi/build.py:ffidestructorbuilder"
    ],
    install_requires=["cffi"],
)
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
