################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
from . import utils
from . import destructors
libapplication_network_destructors = destructors.lib

class AppnetClient(object):
    """

    """

    def __init__(self, parent):
        """
        Appnet-Client
        """
        p = utils.lib.appnet_client_new(parent._p)
        if p == utils.ffi.NULL:
            raise MemoryError("Could not allocate person")

        # ffi.gc returns a copy of the cdata object which will have the
        # destructor called when the Python object is GC'd:
        # https://cffi.readthedocs.org/en/latest/using.html#ffi-interface
        self._p = utils.ffi.gc(p, libapplication_network_destructors.appnet_client_destroy_py)

    @staticmethod
    def new_from_zyre(zyre_evt):
        """
        Create a new appnet_client.
        """
        return utils.lib.appnet_client_new_from_zyre(zyre_evt._p)

    def to_metadata_json_string(self):
        """

        """
        return utils.lib.appnet_client_to_metadata_json_string(self._p)

    def get_name(self):
        """
        get client name
        """
        return utils.lib.appnet_client_get_name(self._p)

    def set_name(self, name):
        """
        set client name
        """
        utils.lib.appnet_client_set_name(self._p, utils.to_bytes(name))

    def get_peer_id(self):
        """
        get client name
        """
        return utils.lib.appnet_client_get_peer_id(self._p)

    def print_py(self):
        """
        print the client info
        """
        utils.lib.appnet_client_print(self._p)

    def parent(self):
        """
        return parent appnet-node
        """
        return utils.lib.appnet_client_parent(self._p)

    @staticmethod
    def test(verbose):
        """
        Self test of this class.
        """
        utils.lib.appnet_client_test(verbose)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
