################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
from __future__ import print_function
import os
import sys
from ctypes.util import find_library

import cffi
ffi = cffi.FFI()

try:
    # If LD_LIBRARY_PATH or your OSs equivalent is set, this is the only way to
    # load the library.  If we use find_library below, we get the wrong result.
    if os.name == 'posix':
        if sys.platform == 'darwin':
            libpath = 'libapplication_network.0.dylib'
        else:
            libpath = 'libapplication_network.so.0'
    elif os.name == 'nt':
        libpath = 'libapplication_network.dll'
    lib = ffi.dlopen(libpath)
except OSError:
    libpath = find_library("application_network")
    if not libpath:
        raise ImportError("Unable to find libapplication_network")
    lib = ffi.dlopen(libpath)

from application_network_cffi.cdefs import application_network_cdefs

for cdef in application_network_cdefs:
   ffi.cdef (cdef)
