################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
NAME        = "application_network"
VERSION     = "0.0.1"
LICENSE     = "mplv2"
DESCRIPTION = """Python bindings of: a network for sharing data and actions in a network"""
URL         = "https://github.com/dertom/applcation-network"
PACKAGES    = ["application_network"]
REQUIRES    = [
    "czmq",
]
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
