/*  =========================================================================
    application_network - generated layer of public API

    Copyright (c) 2021 the Contributors as noted in the AUTHORS file.

    This file is part of application-network, an open-source framework for connecting application and viewers p2p

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef APPLICATION_NETWORK_LIBRARY_H_INCLUDED
#define APPLICATION_NETWORK_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <zyre.h>

//  APPLICATION_NETWORK version macros for compile-time API detection
#define APPLICATION_NETWORK_VERSION_MAJOR 0
#define APPLICATION_NETWORK_VERSION_MINOR 0
#define APPLICATION_NETWORK_VERSION_PATCH 1

#define APPLICATION_NETWORK_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define APPLICATION_NETWORK_VERSION \
    APPLICATION_NETWORK_MAKE_VERSION(APPLICATION_NETWORK_VERSION_MAJOR, APPLICATION_NETWORK_VERSION_MINOR, APPLICATION_NETWORK_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined APPLICATION_NETWORK_STATIC
#       define APPLICATION_NETWORK_EXPORT
#   elif defined APPLICATION_NETWORK_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define APPLICATION_NETWORK_EXPORT __declspec(dllexport)
#       else
#           define APPLICATION_NETWORK_EXPORT
#       endif
#   elif defined APPLICATION_NETWORK_EXPORTS
#       define APPLICATION_NETWORK_EXPORT __declspec(dllexport)
#   else
#       define APPLICATION_NETWORK_EXPORT __declspec(dllimport)
#   endif
#   define APPLICATION_NETWORK_PRIVATE
#elif defined (__CYGWIN__)
#   define APPLICATION_NETWORK_EXPORT
#   define APPLICATION_NETWORK_PRIVATE
#else
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define APPLICATION_NETWORK_PRIVATE __attribute__ ((visibility ("hidden")))
#       define APPLICATION_NETWORK_EXPORT __attribute__ ((visibility ("default")))
#   else
#       define APPLICATION_NETWORK_PRIVATE
#       define APPLICATION_NETWORK_EXPORT
#   endif
#endif

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
typedef struct _appnet_t appnet_t;
#define APPNET_T_DEFINED
typedef struct _appnet_application_t appnet_application_t;
#define APPNET_APPLICATION_T_DEFINED


//  Public classes, each with its own header file
#include "appnet.h"
#include "appnet_application.h"

#ifdef APPLICATION_NETWORK_BUILD_DRAFT_API

#ifdef __cplusplus
extern "C" {
#endif

//  Self test for private classes
APPLICATION_NETWORK_EXPORT void
    application_network_private_selftest (bool verbose, const char *subtest);

#ifdef __cplusplus
}
#endif
#endif // APPLICATION_NETWORK_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
