/*  =========================================================================
    appnet_application - class description

    Copyright (c) 2021 the Contributors as noted in the AUTHORS file.

    This file is part of application-network, an open-source framework for connecting application and viewers p2p

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.
    =========================================================================
*/

#ifndef APPNET_APPLICATION_H_INCLUDED
#define APPNET_APPLICATION_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/appnet_application.api" to make changes.
//  @interface
//  This is a stable class, and may not change except for emergencies. It
//  is provided in stable builds.
//  Appnet-Application
APPLICATION_NETWORK_EXPORT appnet_application_t *
    appnet_application_new (void);

//  Create a new appnet_application.
APPLICATION_NETWORK_EXPORT appnet_application_t *
    appnet_application_new_from_zyre (zyre_event_t *evt, appnet_t *parent);

//  Destroy the appnet_application.
APPLICATION_NETWORK_EXPORT void
    appnet_application_destroy (appnet_application_t **self_p);

//  get application name
APPLICATION_NETWORK_EXPORT const char *
    appnet_application_get_name (appnet_application_t *self);

//  set application name
APPLICATION_NETWORK_EXPORT void
    appnet_application_set_name (appnet_application_t *self, const char *application_name);

//  get zyre peer id
APPLICATION_NETWORK_EXPORT const char *
    appnet_application_get_peer_id (appnet_application_t *self);

//  set zyre peer id
APPLICATION_NETWORK_EXPORT void
    appnet_application_set_peer_id (appnet_application_t *self, const char *peer_id);

//  print application data
APPLICATION_NETWORK_EXPORT void
    appnet_application_print (appnet_application_t *self);

//  add application view ( appnet needs to be set as application-type )
APPLICATION_NETWORK_EXPORT bool
    appnet_application_add_view (appnet_application_t *self, const char *view);

//  get zlist of all views
APPLICATION_NETWORK_EXPORT zlist_t *
    appnet_application_get_view_list (appnet_application_t *self);

//  get zlist of all actions
APPLICATION_NETWORK_EXPORT zlist_t *
    appnet_application_get_action_list (appnet_application_t *self);

//  add application action ( appnet needs to be set as application-type )
APPLICATION_NETWORK_EXPORT bool
    appnet_application_add_action (appnet_application_t *self, const char *action);

//  remote: subscribe for this application's view
APPLICATION_NETWORK_EXPORT void
    appnet_application_remote_subscribe_view (appnet_application_t *self, const char *view_name);

//  remote: unsubscribe from specified view
APPLICATION_NETWORK_EXPORT void
    appnet_application_remote_unsubscribe_view (appnet_application_t *self, const char *view_name);

//  remote: unsubscribe from all views of this application
APPLICATION_NETWORK_EXPORT void
    appnet_application_remote_unsubscribe_all (appnet_application_t *self);

//  remote: trigger action
APPLICATION_NETWORK_EXPORT void
    appnet_application_remote_trigger_action (appnet_application_t *self, const char *action_name, const char *args);

//  get application meta data a string-json
//  Caller owns return value and must destroy it when done.
APPLICATION_NETWORK_EXPORT char *
    appnet_application_to_metadata_json_string (appnet_application_t *self);

//  Self test of this class.
APPLICATION_NETWORK_EXPORT void
    appnet_application_test (bool verbose);

//  @end

#ifdef __cplusplus
}
#endif

#endif
