/*  =========================================================================
    appnet_msg - class description

    Copyright (c) 2021 the Contributors as noted in the AUTHORS file.

    This file is part of application-network, an open-source framework for connecting application and viewers p2p

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.
    =========================================================================
*/

#ifndef APPNET_MSG_H_INCLUDED
#define APPNET_MSG_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/appnet_msg.api" to make changes.
//  @interface
//  This is a draft class, and may change without notice. It is disabled in
//  stable builds by default. If you use this in applications, please ask
//  for it to be pushed to stable state. Use --enable-drafts to enable.
#ifdef APPLICATION_NETWORK_BUILD_DRAFT_API
#define APPNET_MSG_APPLICATION_ENTER 1       //
#define APPNET_MSG_CLIENT_ENTER 2            //

//  *** Draft method, for development use, may change without warning ***
//  Create a new empty appnet_msg
APPLICATION_NETWORK_EXPORT appnet_msg_t *
    appnet_msg_new (zyre_event_t *zyre_event);

//  *** Draft method, for development use, may change without warning ***
//  Destroy a appnet_msg instance
APPLICATION_NETWORK_EXPORT void
    appnet_msg_destroy (appnet_msg_t **self_p);

//  *** Draft method, for development use, may change without warning ***
//  Get Message-Type
APPLICATION_NETWORK_EXPORT uint8_t
    appnet_msg_get_type (appnet_msg_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Get Name
APPLICATION_NETWORK_EXPORT const char *
    appnet_msg_get_name (appnet_msg_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Get views as zlist
APPLICATION_NETWORK_EXPORT zlist_t *
    appnet_msg_get_views (appnet_msg_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Get actions as zlist
APPLICATION_NETWORK_EXPORT zlist_t *
    appnet_msg_get_actions (appnet_msg_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Parse zyre parse zyre event
APPLICATION_NETWORK_EXPORT void
    appnet_msg_parse_zyre_event (appnet_msg_t *self, zyre_event_t *zevent);

//  *** Draft method, for development use, may change without warning ***
//  Self test of this class.
APPLICATION_NETWORK_EXPORT void
    appnet_msg_test (bool verbose);

#endif // APPLICATION_NETWORK_BUILD_DRAFT_API
//  @end

#ifdef __cplusplus
}
#endif

#endif
