/*  =========================================================================
    appnet_msg - class description

    Copyright (c) 2021 the Contributors as noted in the AUTHORS file.

    This file is part of application-network, an open-source framework for connecting application and viewers p2p

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.
    =========================================================================
*/

#ifndef APPNET_MSG_H_INCLUDED
#define APPNET_MSG_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/appnet_msg.api" to make changes.
//  @interface
//  This is a draft class, and may change without notice. It is disabled in
//  stable builds by default. If you use this in applications, please ask
//  for it to be pushed to stable state. Use --enable-drafts to enable.
#ifdef APPLICATION_NETWORK_BUILD_DRAFT_API
#define APPNET_MSG_FIELD_TYPE "msg_type"     //
#define APPNET_MSG_TYPE_TRIGGER_ACTION "trigger_action"  //
#define APPNET_MSG_FIELD_ACTION_NAME "action_name"  //
#define APPNET_MSG_FIELD_ACTION_ARGS "action_args"  //

//  *** Draft method, for development use, may change without warning ***
//  Create trigger action msg (as json)
//  Caller owns return value and must destroy it when done.
APPLICATION_NETWORK_EXPORT char *
    appnet_msg_create_trigger_action (const char *action_name, const char *args);

//  *** Draft method, for development use, may change without warning ***
//  Self test of this class.
APPLICATION_NETWORK_EXPORT void
    appnet_msg_test (bool verbose);

#endif // APPLICATION_NETWORK_BUILD_DRAFT_API
//  @end

#ifdef __cplusplus
}
#endif

#endif
