/*  =========================================================================
    appnet_client - class description

    Copyright (c) 2021 the Contributors as noted in the AUTHORS file.

    This file is part of application-network, an open-source framework for connecting application and viewers p2p

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.
    =========================================================================
*/

#ifndef APPNET_CLIENT_H_INCLUDED
#define APPNET_CLIENT_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/appnet_client.api" to make changes.
//  @interface
//  This is a stable class, and may not change except for emergencies. It
//  is provided in stable builds.
//  Appnet-Client
APPLICATION_NETWORK_EXPORT appnet_client_t *
    appnet_client_new (void);

//  Destroy the appnet_client.
APPLICATION_NETWORK_EXPORT void
    appnet_client_destroy (appnet_client_t **self_p);

//  set client name
APPLICATION_NETWORK_EXPORT void
    appnet_client_set_name (appnet_client_t *self, const char *name);

//  Self test of this class.
APPLICATION_NETWORK_EXPORT void
    appnet_client_test (bool verbose);

//  @end

#ifdef __cplusplus
}
#endif

#endif
