The following ABNF grammar defines the work with appnet messages:

    appnet_msg      = *( ENTER | CLIENT-ENTER )

    ;  No description

    ENTER           = signature %d1 version sequence app_name app_views app_actions
    signature       = %xAA %xA1             ; two octets
    version         = number-1              ; Version number (2)
    sequence        = number-2              ; Cyclic sequence number
    app_name        = string                ; Name of the entered application
    app_views       = zlist                 ; views
    app_actions     = string                ; actions

    ;  No description

    CLIENT-ENTER    = signature %d2 version sequence client_name app_views app_actions
    version         = number-1              ; Version number (2)
    sequence        = number-2              ; Cyclic sequence number
    client_name     = string                ; Name of the entered client
    app_views       = string                ; views
    app_actions     = string                ; actions

    ; Strings are always length + text contents
    string          = number-1 *VCHAR

    ; Numbers are unsigned integers in network byte order
    number-1        = 1OCTET
    number-2        = 2OCTET
